#!/bin/bash

REPOSITORY=$1
VERSION=$2
MODE=$3
ARGCOUNT=0

for var in "$@"; do 
    (( ARGCOUNT++ ))
done

if (( $ARGCOUNT < 2 || $ARGCOUNT > 3 )); then
    echo "Invalid number of args"
    echo "$*"
elif [[ ! $(echo $VERSION|grep "^[0-9A-Z_]\+/[0-9A-Z_]\+-\([0-9]\+\|latest\)$") ]]; then
    echo "Version $VERSION is not valid"
    exit 1
fi

if [[ -f /DATYPE ]]; then
  /usr/local/storediq/bin/fastupdate.py $VERSION
else
  /spinmini --noreboot $VERSION s gw
fi

if [[ $MODE == production ]]; then
  service deepfiler start
elif [[ $MODE == idle ]]; then
  service deepfiler stop
fi

