#!/bin/bash

REPOSITORY=$1
VERSION=$2
MODE=$3

if [[ -f /DATYPE ]]; then
  /usr/local/storediq/bin/fastupdate.py
else
  /spinmini --noreboot TRUNK/STOREDIQ s gw
fi

if [[ $MODE == production ]]; then
  service deepfiler start
elif [[ $MODE == idle ]]; then
  service deepfiler stop
fi
